name: test_track
description: The dart client for the TestTrack system. It provides client-side split-testing and feature-toggling through a simple API.
version: 0.3.0
homepage: https://github.com/Betterment/test_track_dart_client
repository: https://github.com/Betterment/test_track_dart_client

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  dart_mappable: ^4.6.1
  dio: ^5.9.0
  equatable: ^2.0.7
  meta: ^1.17.0
  sturdy_http: ^0.6.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  charlatan: ^0.5.0
  coverage: ^1.15.0
  dart_mappable_builder: ^4.6.3
  fake_async: ^1.3.3
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.28.0
  test_track_test_support:
    path: ../test_track_test_support
