name: test_track_test_support
description: Test utilities for working with package:test_track, including a FakeTestTrack allowing you to test your integration with TestTrack with predetermined behavior.
version: 0.2.0
homepage: https://github.com/Betterment/test_track_dart_client
repository: https://github.com/Betterment/test_track_dart_client

resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  meta: ^1.17.0
  random_string: ^2.3.1
  test_track: ^0.2.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.28.0
