name: test_track_test_support
description: Test utilities for working with package:test_track, including a FakeTestTrack allowing you to test your integration with TestTrack with predetermined behavior.
version: 0.3.1
homepage: https://github.com/Betterment/test_track_dart_client
repository: https://github.com/Betterment/test_track_dart_client

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  equatable: ^2.0.8
  meta: ^1.16.0
  random_string: ^2.3.1
  test_track: ^0.3.2

dev_dependencies:
  coverage: ^1.15.0
  lints: ^5.1.1
  test: ^1.29.0
